version: 0.5
author: Vraken
main: fr.vraken.thepurgeofsalem.ThePurgeOfSalem
description: Plugin de The Purge of Salem
name: VrakenThePurgeOfSalem
commands:
  gotstart:
    description: Commencer la partie
    usage: /gotstart
  gotload:
    description: Charger une partie enregistree
    usage: /gotload
  gotstop:
    description: Arrêter la partie
    usage: /gotstop
  gotmeetup:
    description: Rassembler les joueurs avant le lancement
    usage: /gotmeetup
  t:
    description: Pour parler entre taupes !
    usage: /t
  reveal:
    description: Pour vous reveler en tant que taupe !
    usage: /reveal
  claim:
    description: Pour réclamer votre kit de taupe !
    usage: /claim
  gotspec:
    description: Passer en mode spectateur
    usage: /gotspec
  gotlobby:
    description: Passer en mode aventure dans le lobby
    usage: /gotlobby